### ISSUE TITLE
[Suggestion] An idea for a homepage redesign

### ISSUE THREAD

**Issue by ItzaMi** [surface-ui/surface_site#65]
Hi 👋 I'm a self-taught front end developer that recently started learning about Elixir and Phoenix and while I was progressing people kept suggesting Surface and here I am 😄 It's honestly amazing to see the effort that went into creating the library and how much value it has for the community so I'm excited to see it grow in the upcoming times.

When I stepped into https://surface-ui.org/, the UI, for me, didn't feel very modern and attractive and I was wondering if we could do some tweaks to it to boost its looks and make the starting experience of navigating the docs more exciting!

I have two suggestions for the homepage, one with just a simple intro ( v1 ) and another that is more informative and tries to go towards a similar look to other component libraries' websites.

Let me know if this is something that you could be interested in and I can get to work! 😄

[The figma file](https://www.figma.com/file/BLapVKNnpuT5KNbqUAEBAV/Surface-UI?node-id=0%3A1)

**V1**
![V1](https://user-images.githubusercontent.com/30603437/167796051-0fb9b7a3-5bb1-4381-9a8d-a213ef65118a.jpeg)

**V2**
![V2](https://user-images.githubusercontent.com/30603437/167796122-c55fd936-5ee7-4b7a-8495-cf4f4564ccca.jpeg)

**Comment by msaraiva** [comment]
Hi @ItzaMi!

Sorry for the late reply. I love the idea! We sure need to put more effort to our website. There's even a related discussion on having an [official logo for Surface](https://github.com/surface-ui/surface/issues/287), which would probably also bring a nicer look to it. We also have plans to update both, the website and the catalogue using TailwindCSS but due to time constraints, this always has be put aside. In case you're still willing to help us, I'd definitely appreciate it. Let me know if still have time and interest to work on this so I can bring a couple of other folks to the discussion.

Thank you!

**Comment by ItzaMi** [comment]
Hey, @msaraiva !
100% interested in helping! Still have time (other than this and next week - 1st to 10th of June,  since I'll be on vacations but other than that, let's do it!

**Comment by msaraiva** [comment]
The logo has been chosen!

Also related https://github.com/surface-ui/surface/issues/643.

**Comment by ItzaMi** [comment]
I have closed this issue but I'm still open to deal with the redesign FYI
