### ISSUE TITLE
Event section is confusing

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface_site#7]
I am reading the Event section again and again and to be honest I am more an more lost :sweat_smile: 

The purpose of this issue is to list what I find strange in the Event section in order to share my feeling before attacking and validating a possible rewrite. I tried to take the point of view of a beginner and I tried to forget how to use events in Surface.

_\<Mode Beginner On\>_

### Purpose of the default value
This section is related to the one below, but I was wondering what type should be the "default" option? String? Function?

### Use cases
The use cases of the `prop click, :event` are not clear. We use a quick example that shows how to declare a prop event but we do not know if the event is internal to the component or if we should pass a function to that prop.

```elixir
  defmodule MyButton do
    use Surface.Component

    @doc "Triggers on click"
    prop click, :event

    def render(assigns) do
      ...
    end
  end
```

This confusion is accentuated the next examples: _Handling events in Surface/LiveView_. In these examples, a prop event has not been declared but some `handle_event` functions have been declared. Moreover, reader also finds this sentence: "always declare event properties as :event" but it is not the case in the example. :confused:

Some questions raise in my mind:

- Should we use both?
- If so, when should I declare a prop event?
- Are these use cases not the same one?
- Are the name used  in `:on-{name}` the same as the one used in `prop {name}, :event`? 

### Use of the "click" event only

I suggest to add examples with other events (at least one): `keyup`, `keydown`, `debounce`, ...

`phx-click` is often used with `phx-value`:

```html
<div phx-click="inc" phx-value-myvar1="val1" phx-value-myvar2="val2">
```
will send the following map of params to the server ([doc](https://hexdocs.pm/phoenix_live_view/bindings.html#click-events)):
```elixir
def handle_event("inc", %{"myvar1" => "val1", "myvar2" => "val2"}, socket) do
```

In that case, it's not clear in Surface if I should use `phx-value-myvar` or `:on-value-my-var`. The last one seems strange to me.

_\<Mode Beginner Off\>_

I am wondering if we should rewrite this section to be more explicit and less confusing? For example, we could base the rewriting on the examples in the tests and improve them to show the "flow":

```elixir
defmodule Button do
    use Surface.LiveComponent

    prop click, :event, default: "click"

    def render(assigns) do
      ~H"""
      <button :on-click={{ @click }}>Click me!</button>
      """
    end

    def handle_event("click", _, socket) do
      {:noreply, socket}
    end
  end

  defmodule Panel do
    use Surface.LiveComponent

    prop buttonClick, :event, default: "click"

    def render(assigns) do
      ~H"""
      <div>
        <Button id="button_id" click={{ @buttonClick }}/>
      </div>
      """
    end

    def handle_event("click", _, socket) do
      {:noreply, socket}
    end
  end

  # Example without default value
  defmodule View do
    use Surface.LiveView

    def render(assigns) do
      ~H"""
      <div>
        <Panel id="panel_id" buttonClick="click"/>
      </div>
      """
    end

    def handle_event("click", _, socket) do
      {:noreply, socket}
    end
  end

  # Example with default value
  defmodule View do
    use Surface.LiveView

    def render(assigns) do
      ~H"""
      <div>
        <Panel id="panel_id" />
      </div>
      """
    end
  end
```

I believe we should highlight some points:

- the name of the prop is not correlated to the Phoenix Event name
- the list of phoenix live view events is fixed, you cannot create new event
- the prop event could have a default value that is the first argument of the `handle_event` method you would like to use
- the event you want to pass through the prop follow the same assumption
- you can pass event in nested components
- show an example with a component that has multiple events (cancel and add buttons for example)
- if the event is an "internal" event to the component, you do not have to declare `prop name, :event`

Feel free to comment and add your feeling about this section. Even if my English level is not perfect, I would be glad to take time to rewrite this section the best I can.

**Comment by msaraiva** [comment]
Hi @Malian!

> I was wondering what type should be the "default" option? String? Function?

The purpose of the default value is mostly to be used in LiveComponents whenever you're able to have a default implementation for the event but you also want to allow users to override it with their own implementation, if necessary. In 99% of the cases (maybe 100%), it would be a string, which will set the `phx-target` to `@myself`. If you don't want to allow users to add their own implementation, then you shouldn't expose it as a property and just pass that same string to `phx-[event]`.

> The use cases of the prop click, :event are not clear. We use a quick example that shows how to declare a prop event but we do not know if the event is internal to the component or if we should pass a function to that prop.

Agreed. We should add an element with `:on-click={{ @click }}`

> This confusion is accentuated the next examples: _Handling events in Surface/LiveView_. In these examples, a prop event has not been declared but some `handle_event` functions have been declared.

Defining a `handle_event` and declaring a prop as `:event` are independent actions. In general, you only need to declare a prop if you expect the user to pass some information using that prop. In case of events, if you're handling them yourself and you don't allow users to override the implementation, there's no need to define a prop, just a `handle_event`. In our example, since we said "Let's rewrite our example again using Surface's :on-click directive:", we just have:

```
# Event handlers
    ...
```

indicating the handlers haven't changed from the previous example. I usually prefer that, otherwise, we force the user to read more code to find the differences themselves. I might be wrong then :)

> Some questions raise in my mind:
> 
> * Should we use both?

It depends on your needs.

> * If so, when should I declare a prop event?

Only if you're not handling the event or if you want a parent component to be able to pass an alternative implementation.

> * Are these use cases not the same one?

Not sure what you mean but both examples, the vanilla LV and Surface one should work the same way at the end.

> * Are the name used  in `:on-{name}` the same as the one used in `prop {name}, :event`?

No, no, no. It's up to the component's author to define that. Imagine you have a dialog where you have two buttons and you want the user to implement both click events, for the `Cancel` and the `Ok` buttons. You'd need to define two different properties. One for each button, something like:

```elixir
prop cancel, :event, required: true
prop ok, :event, required: true

def render(assigns) do
  ~H"""
  ...
  <footer>
    <button :on-click={{ @cancel }}>Cancel</button>
    <button :on-click={{ @ok }}>Ok</button>
  </footer>
  """
end
```

In this case, the Dialog itself is not handing any of those events, so the user must pass them.

> I suggest to add examples with other events (at least one): `keyup`, `keydown`, `debounce`, ...

Agreed. We just need to make sure we don't rewrite the LV's docs. The goal is to just point the differences between Surface and LV on events. All the rest should work just like in LV which is already well documented.

> it's not clear in Surface if I should use `phx-value-myvar` or `:on-value-my-var`. The last one seems strange to me.

The last one doesn't exist :)

Directives like those are mostly implemented for syntactic sugar. They just generate code for you. That's exactly the case of `:on-[event]` which automatically generates both `phx-[event]` and `phx-target`.  So the general rule is: if there's a directive for it, use it as it should provide better DX. Otherwise, just use whatever `phx-` already exists. We don't want to create directives that just map their `phx-` counterparts as it would just add more code to maintain with no real benefit. We only add a new directive if it actually does something extra and that's not the case of `:phx-value-*`. There are plans to create a `:values` directive that could receive the values as a keyword list and convert them to individual `phx-value-*` but we haven't done that yet :) 

> I am wondering if we should rewrite this section to be more explicit and less confusing? For example, we could base the rewriting on the examples in the tests and improve them to show the "flow":

Sure we could.

> I would be glad to take time to rewrite this section the best I can.

That would be awesome! Thanks.

**Comment by jasonmj** [comment]
> Agreed. We should add an element with :on-click={{ @click }}

This would help a lot. I was having trouble with the docs until I found this issue.

**Comment by msaraiva** [comment]
I moved the `:event` prop section to the "Properties" page which makes it more consistent with other special types like `:css_class`. I also updated the example to use the event with `:on-click={{ @click }}`.  Change can be found on master.

**Comment by LuisMiguelMelo** [comment]
Everything is confusing in that documentation

**Comment by Malian** [comment]
Hi @LuisMiguelMelo 

I can understand part of your point of view as I am the author of this issue and the PR that tried to reduce the confusion I mentioned. Other community members sometimes have the same feeling and they try to improve the doc step by step with small PR or by giving us suggestions.

We know that there is room for improvement with Surface’s docs in many places, but writing documentation is hard, and your comment does not give us something to work with.

In order to be more constructive, could you point out the elements in the doc that you find confusing and that we could improve? Better, how could we improve them?

Of course "everything" is not a valid answer ;)
